[package]
name = "rust-nes-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.0.2"
log = "0.4"
simple-logging = "2.0.2"
sdl2 = "0.35.2"
env_logger = "0.10.1"
fern = "0.6.2"
